print("Iltimos quyidagi ma'lumotlarni kiriting: ")
ism = input("Ismingiz : >>> ")
sharif = input("Familiyangiz : >>>")
yosh = input("Yoshingiz : >>>")
s_m = f"Ismingiz {ism}, familiyangiz {sharif}, yoshingiz {yosh}"
print(s_m)
print(s_m.upper())
print(s_m.title())
print(s_m.lower())
davlat = input("Qaysi davlatdansiz : >>>")
viloyat = input("Viloyatingiz : >>>")
tuman = input("Tumaningiz : >>>")
info = input("O'qiysizmi : >>>")
info2 = input("Ishlaysizmi : >>>")
m_info = (f"{davlat} davlati, {viloyat} viloyati, {tuman} tumani, \t {info} degansiz, {info2} degansiz"
          f" \n Malu'motingiz uchun rahmat")
print(m_info)
print(m_info.lower())
print(m_info.title())
